// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNO86Z6RiYN7J1uxWYCs-Bqdrk61yZc8U',
    appId: '1:146203294237:web:6ab756edf838a316a564f4',
    messagingSenderId: '146203294237',
    projectId: 'contacts-test-12',
    authDomain: 'contacts-test-12.firebaseapp.com',
    storageBucket: 'contacts-test-12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElWjy1YvV3Y7hfz8mMktgI41XryVFcq0',
    appId: '1:146203294237:android:f7400784ce2f1c17a564f4',
    messagingSenderId: '146203294237',
    projectId: 'contacts-test-12',
    storageBucket: 'contacts-test-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAui4vdwGKeN0uQzJpQcthSseuyMw6Kmvk',
    appId: '1:146203294237:ios:62492cb80c28aaffa564f4',
    messagingSenderId: '146203294237',
    projectId: 'contacts-test-12',
    storageBucket: 'contacts-test-12.appspot.com',
    iosClientId: '146203294237-mb5p5vb4k1ujll63jc4lm7o0ir6sseaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.contacts',
  );
}
